# Generated by Django 5.2.14 on 2026-05-16 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shop', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('picture', models.URLField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
